name: Action Branch Main

on:   
  push:
    branches:
      - develop
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World Main Branch!"
